# Generated by Django 4.0.1 on 2022-04-24 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('bookId', models.IntegerField(primary_key=True, serialize=False)),
                ('BookName', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('horror', 'horror'), ('comedy', 'comedy'), ('sci-fi', 'sci-fi'), ('romantic', 'romantic'), ('technology', 'technology'), ('other', 'other')], default='none', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderId', models.IntegerField(primary_key=True, serialize=False)),
                ('IssueDate', models.DateTimeField()),
                ('returnDate', models.DateTimeField()),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.books')),
                ('full_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.users')),
            ],
        ),
    ]
